CREATE TABLE IF NOT EXISTS analysis_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    final_score INT NOT NULL DEFAULT 0,
    mandatory_score INT NOT NULL DEFAULT 0,
    bonus_score INT NOT NULL DEFAULT 0,
    matched_skills TEXT,
    missing_skills TEXT,
    candidate_data TEXT,
    job_data TEXT,
    raw_cv_text TEXT,
    raw_job_description TEXT
);
